### ISSUE TITLE
Clean UP & Dockerization eos2gth

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos2gth#10]

**Comment by GemmaTuron** [comment]
@HellenNamulinda 
The model has failed the test please check

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron, 
The Model Test on push is failing at predict output(serving model) with `CondaEnvironmentService' object has no attribute 'pid`, which is likely the port id!. 
```
11:43:42 | DEBUG    | Cleaning temp dir
11:43:42 | DEBUG    | Silencing docker containers if necessary
11:43:43 | DEBUG    | It is not inside docker
Checking setup: 0.175s
Preparing model: 3.2839248180389404s
Getting model: 0.022433042526245117s
Packing model: 90.8594069480896s
Checking if model needs to be integrated to a tool: 0.001[877](https://github.com/ersilia-os/eos2gth/actions/runs/5389331384/jobs/9783139002#step:10:878)5463104248047s
Getting model card: 0.05251622200012207s
[]
Checking that autoservice works: 2.5646913051605225s
🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

'CondaEnvironmentService' object has no attribute 'pid'
```
I have not yet figured out the cause because all packages install correctly and the model passed the [Model Test on PR](https://github.com/ersilia-os/eos2gth/actions/runs/5388555336/jobs/9781370705)

Comparing the two, on push checks whether it is [inside docker](https://github.com/ersilia-os/eos2gth/actions/runs/5389331384/jobs/9783139002#step:10:871), `11:43:43 | DEBUG    | It is not inside docker`, but on PR  was [serving with BentoML](https://github.com/ersilia-os/eos2gth/actions/runs/5388555336/jobs/9781370705#step:8:807) `Trying to serve model with BentoML locally`
```
10:16:43 | DEBUG    | Cleaning temp dir
10:16:43 | DEBUG    | Silencing docker containers if necessary
10:16:44 | DEBUG    | Trying to serve model with BentoML locally
10:16:44 | WARNING  | Port None was already in use. Using 50959 instead
10:16:44 | DEBUG    | Free port: 50959
10:16:44 | DEBUG    | Writing on /tmp/ersilia-fayaohwr/serve.sh
10:16:44 | DEBUG    | #!/bin/bash
10:16:44 | DEBUG    | bentoml serve eos2gth:20230627101633_CDBC3C --port 50959 &> /tmp/ersilia-fayaohwr/serve.log &
10:16:44 | DEBUG    | _pid=$!
10:16:44 | DEBUG    | echo "$_pid" > /tmp/ersilia-fayaohwr/serve.pid
10:16:44 | DEBUG    | Run command function available
10:16:45 | DEBUG    | Running on conda environment eos2gth
10:16:45 | DEBUG    | Run commandlines on eos2gth
10:16:45 | DEBUG    | bash /tmp/ersilia-fayaohwr/serve.sh
10:16:46 | DEBUG    | Activating base environment
10:16:46 | DEBUG    | Current working directory: /home/runner/work/eos2gth/eos2gth
```

**Comment by HellenNamulinda** [comment]
> Hello @HellenNamulinda ! Can we try now? I think I have solved the issue (entirely my fault)

@miquelduranfrigola,
Won't that require rerunning the jobs manually?
I don't know how to do it.

**Comment by GemmaTuron** [comment]
I've re run the jobs successfully!

**Comment by miquelduranfrigola** [comment]
I am rerunning the dockerhub workflow now. Let's see: https://github.com/ersilia-os/eos2gth/actions/runs/5391240982
